In [13]:
import numpy as np

In [47]:
# Generar numeros aleatorios
r = np.random.rand(3,3)
print(r)
print(f"shape :{r.shape}")
print(f"size :{r.size}")
print(f"ndim :{r.ndim}")

[[0.70740992 0.01901622 0.78120585]
 [0.60156756 0.98767134 0.95441364]
 [0.39530131 0.42328243 0.95232257]]
shape :(3, 3)
size :9
ndim :2


## Basics

In [32]:
# Basic array
a = np.array([1, 2, 3])
print(a)
print(a.shape)

[1 2 3]
(3,)


![title](img/basic_array.png)

In [33]:
#array de zeros y unos
print(f"Array zeros: {np.zeros(10)}")
print(f"Array ones: {np.ones(10)}")
print(f"Array arange: {np.arange(2, 9, 2)}")

Array zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array arange: [2 4 6 8]


In [53]:
# SORT function
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8], dtype=np.float64)
arr.sort()
arr

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [41]:
# Concatenate
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
#
print(np.concatenate((a, b)))
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
#
print(np.concatenate((x, y), axis=0))

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]]


In [84]:
# Reshape array
a = np.arange(12)
print(a)
print(a.reshape(3, 4))
print(a[np.newaxis,:])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


In [88]:
# Expand dimension
a = np.expand_dims(np.arange(12), axis=0)
print(f"A: {a}")
print(a.shape)
b = np.expand_dims(np.arange(12), axis=1)
print(f"B: {b}")
print(b.shape)

A: [[ 0  1  2  3  4  5  6  7  8  9 10 11]]
(1, 12)
B: [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
(12, 1)


## Indexing and Slicing

![title](img/slicing.png)
![title](img/slicing_matrix.png)

In [100]:
data = np.array([1,2,3])
#
print(f"Index[1]: {data[1]}")
print(f" {data[0:2]}")
print(f" {data[-2:]}")

Index[1]: 2
 [1 2]
 [2 3]


In [174]:
data = np.random.randint(low=1,high=16,size=(4, 4))
print(data)
#
print(f"numeros mayores que 6 :{np.sort(data[data>6])}")
#
print(f"numeros pares :{data[data%2==0]}")
#
print(f"numeros entre 6 y 10 :{data[(data>=6) & (data<=10)]}")

[[ 1  8  6 13]
 [ 8 14  5  7]
 [ 2 11  4  2]
 [11  8  1 14]]
numeros mayores que 6 :[ 7  8  8  8 11 11 13 14 14]
numeros pares :[ 8  6  8 14  2  4  2  8 14]
numeros entre 6 y 10 :[8 6 8 7 8]


In [181]:
test = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]).reshape(4,4)
list(zip(*test))

[(1, 5, 9, 13), (2, 6, 10, 14), (3, 7, 11, 15), (4, 8, 12, 16)]

## Operaciones

In [191]:
# Operaciones
print(f"Operacion suma:{data+data}")
print(f"Operacion resta:{data-data}")
print(f"Operacion multiplicacion:{data*data}")
print(f"Operacion multiplicacion escalar:{data*1.6}")
print(f"Operacion division:{data/data}")

Operacion suma:[[ 2 16 12 26]
 [16 28 10 14]
 [ 4 22  8  4]
 [22 16  2 28]]
Operacion resta:[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Operacion multiplicacion:[[  1  64  36 169]
 [ 64 196  25  49]
 [  4 121  16   4]
 [121  64   1 196]]
Operacion multiplicacion escalar:[[ 1.6 12.8  9.6 20.8]
 [12.8 22.4  8.  11.2]
 [ 3.2 17.6  6.4  3.2]
 [17.6 12.8  1.6 22.4]]
Operacion division:[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [234]:
def operation(array,function,axis=None):
    if axis==0:
        return f"Function columns {function.__name__}: {function(array,axis=axis)}"
    elif axis==1:
        return f"Function rows {function.__name__}: {function(array,axis=axis)}"
    else:
        return f"Function {function.__name__}: {function(array,axis=axis)}"

a = np.array([[1, 3], [2, 2]])
print(a)
# sumar
print(operation(a,np.sum))
print(operation(a,np.sum,axis=0))
print(operation(a,np.sum,axis=1))
#
print(operation(a,np.min))
print(operation(a,np.min,axis=0))
print(operation(a,np.min,axis=1))
#
print(operation(a,np.max))
print(operation(a,np.max,axis=0))

[[1 3]
 [2 2]]
Function sum: 8
Function columns sum: [3 5]
Function rows sum: [4 4]
Function amin: 1
Function columns amin: [1 2]
Function rows amin: [1 2]
Function amax: 3
Function columns amax: [2 3]


In [237]:
# Valores unicos
print(operation(a,np.unique))
print(operation(a,np.unique,axis=0))
print(operation(a,np.unique,axis=1))
#
print(np.unique(a, return_index=True))
print(np.unique(a, return_counts=True))

Function unique: [1 2 3]
Function columns unique: [[1 3]
 [2 2]]
Function rows unique: [[1 3]
 [2 2]]
(array([1, 2, 3]), array([0, 2, 1], dtype=int64))
(array([1, 2, 3]), array([1, 2, 1], dtype=int64))


In [251]:
# Transpuesta
print(a.T)
print(operation([1,2,3],np.flip))
print(operation(a,np.flip,axis=0))
print(operation(a,np.flip,axis=1))
print(a.flatten())

[[1 2]
 [3 2]]
Function flip: [3 2 1]
Function columns flip: [[2 2]
 [1 3]]
Function rows flip: [[3 1]
 [2 2]]
[1 3 2 2]
