In [2]:
import pandas as pd
import numpy as np

In [6]:
a = np.array([1,2,3,4,5])
print(a)
np.save('a.npy', a)
a = np.load('a.npy')
print(a)

[1 2 3 4 5]
[1 2 3 4 5]


In [13]:
csv = np.array([[1,2,3],[4,5,6]],dtype=np.uint8)
print(csv)
# Guardar archivo csv
np.savetxt('file.csv', csv, delimiter=',', fmt='%.2f', header='x,y,z')
csv = np.loadtxt('file.csv', delimiter=',')
print(csv)

[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [61]:
dataset = pd.read_csv('EstacionesTroncal.csv', encoding='utf-8').values
print(f"shape :{dataset.shape}")
print(f"size :{dataset.size}")
print(f"ndim :{dataset.ndim}")

shape :(149, 5)
size :745
ndim :2


In [63]:
for i in range(dataset.shape[1]):
    print(dataset[:,i])

[61 98 103 149 64 62 58 18 65 74 73 63 101 96 37 48 25 46 35 50 147 20 34
 45 36 38 148 47 49 24 150 21 33 22 40 32 42 29 31 44 28 41 30 43 151 9 6
 17 7 13 19 12 16 26 27 10 11 152 23 145 60 59 15 146 89 14 107 72 95 71
 92 83 82 80 90 87 88 93 79 77 97 84 78 81 91 94 153 127 128 133 131 134 1
 129 5 130 3 2 132 86 85 4 135 154 118 137 119 136 114 115 111 112 124 139
 120 116 113 117 155 156 99 100 68 106 57 144 54 53 108 56 109 52 55 70 69
 66 67 157 125 123 105 140 138 122 104 143 102 142 158]
[' Avenida 39 ' ' Avenida Jiménez ' 'Calle 22' ' Calle 26 ' 'Calle 57'
 'Calle 45' 'Calle 34' 'Calle 76' 'Calle 63' 'Calle 72' 'Flores' 'Marly'
 'Calle 19' 'Tercer Milenio' 'Calle 127' 'Mazurén' 'Virrey' 'Calle 142'
 'Calle 106' 'Toberí\xadn' 'Terminal' 'Héroes' 'Calle 100' 'Alcalá'
 'Pepe Sierra' 'Prado' 'Calle 187' 'Calle 146' 'Calle 161' 'Calle 85'
 'Portal Norte' 'San Martín' 'Puentelargo' 'Rionegro' 'Suba - Tv. 91'
 'Suba - Calle 95' 'Suba – Avenida Boyacá' 'Humedal Córdoba'
 'Suba - Call

In [46]:
# strip 
strip_numpy = np.vectorize(lambda x: x.strip())
dataset[:,1] = strip_numpy(dataset[:,1])
dataset[0,1]

'Avenida 39'

In [60]:
# strip
np.char.strip(dataset[:,1].astype(str))

array(['Avenida 39', 'Avenida Jiménez', 'Calle 22', 'Calle 26',
       'Calle 57', 'Calle 45', 'Calle 34', 'Calle 76', 'Calle 63',
       'Calle 72', 'Flores', 'Marly', 'Calle 19', 'Tercer Milenio',
       'Calle 127', 'Mazurén', 'Virrey', 'Calle 142', 'Calle 106',
       'Toberí\xadn', 'Terminal', 'Héroes', 'Calle 100', 'Alcalá',
       'Pepe Sierra', 'Prado', 'Calle 187', 'Calle 146', 'Calle 161',
       'Calle 85', 'Portal Norte', 'San Martín', 'Puentelargo',
       'Rionegro', 'Suba - Tv. 91', 'Suba - Calle 95',
       'Suba – Avenida Boyacá', 'Humedal Córdoba', 'Suba - Calle 100',
       '21 Ángeles', 'Shaio', 'La Campiña', 'Niza - Calle 127',
       'Gratamira', 'Portal de Suba', 'Minuto de Dios', 'Quirigua',
       'Escuela Militar', 'Carrera 90', 'Carrera 53', 'Polo',
       'Granja - Carrera 77', 'Carrera 47', 'Ferias', 'Avenida 68',
       'Avenida Boyacá', 'Avenida Ciudad de Cali', 'Portal de la 80',
       'Castellana', 'Guatoque – Veraguas', 'Campín-UAN',
       'Universid

In [71]:
dataset[:,-1] = dataset[:,-1].astype('datetime64')
dataset[0,-1]

datetime.date(2021, 7, 11)